// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFz-7-y6y92EaKJI_V3CQ4IA0H-l6GWE',
    appId: '1:388114013097:web:e1f17d693350a12168c2b8',
    messagingSenderId: '388114013097',
    projectId: 'movie-app-7c43c',
    authDomain: 'movie-app-7c43c.firebaseapp.com',
    storageBucket: 'movie-app-7c43c.appspot.com',
    measurementId: 'G-HQ53JHX1Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTk_BHupnQrb6lxqK76aetT1SArLIp6vs',
    appId: '1:388114013097:android:0ae88130c8032b5068c2b8',
    messagingSenderId: '388114013097',
    projectId: 'movie-app-7c43c',
    storageBucket: 'movie-app-7c43c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYu_DyAh0creccNSwibQ91X4OFP2pKi38',
    appId: '1:388114013097:ios:5f46842335bb7bf768c2b8',
    messagingSenderId: '388114013097',
    projectId: 'movie-app-7c43c',
    storageBucket: 'movie-app-7c43c.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYu_DyAh0creccNSwibQ91X4OFP2pKi38',
    appId: '1:388114013097:ios:cee751fd280a6f4e68c2b8',
    messagingSenderId: '388114013097',
    projectId: 'movie-app-7c43c',
    storageBucket: 'movie-app-7c43c.appspot.com',
    iosBundleId: 'com.',
  );
}
